{% set version = "{{cookiecutter.version}}" %}

package:
  name: {{cookiecutter.project_slug}}
  version: \{\{ version \}\}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=\{\{ version \}\}
  {%- if cookiecutter.project_shell_cmd %}
  entry_points:
    - {{ cookiecutter.project_shell_cmd }} = '{{ cookiecutter.project_slug }}.cli:cli'
  {%- endif %}
  script: "\{\{ PYTHON \}\} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >= 61.0
  run:
    - python >=3.7
    - setuptools  # uses pkg_resources

about:
  home: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}.git
  license: {{cookiecutter.open_source_license}}
  summary: '{{ cookiecutter.project_short_description }}'
  license_file: LICENSE
