{% set version = "{{cookiecutter.version}}" %}

package:
  name: {{cookiecutter.project_slug}}
  version: \{\{ version \}\}

source:
  url: https://files.pythonhosted.org/packages/ef/95/aa7e6d1c1b68e64234d5ed985a761edbbce124baea17c2056935626958d2/pyfaidx-0.8.0.tar.gz
  sha256: 1eed70f4eafb4ba9c4cf7022cd748947b8ebe0f4c86cb56f42f587ab7f2da027

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=\{\{ version \}\}
  {%- if cookiecutter.project_shell_cmd %}
  entry_points:
    - {{ cookiecutter.project_shell_cmd }} = '{{ cookiecutter.project_slug }}.cli:cli'
  {%- endif %}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >= 61.0
  run:
    - python >=3.7
    - setuptools  # uses pkg_resources

about:
  home: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.projectslug}}.git
  license: {{cookiecutter.open_source_license}}
  summary: '{{ cookiecutter.project_short_description }}'
  license_file: LICENSE