name: Test Cookiecutter Template

on: [push, pull_request]

jobs:
  test-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Cookiecutter
      run: pip install cookiecutter

    - name: Generate a fake project from the template
      run: cookiecutter . --no-input full_name="John Doe" email="jondoe@email.email" github_username="johndoe" project_name="Test Project" open_source_license="Public domain"

    - name: Navigate to generated project directory
      run: cd $(ls -d */ | head -n 1)

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run tests
      run: make test